name: Whiskit

on: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository contents
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install libboost-all-dev freeglut3-dev mesa-utils libyaml-cpp-dev

      - name: Build Whiskit
        run: |
          mkdir whiskit-build
          cd whiskit-build
          cmake ${GITHUB_WORKSPACE}/code
          make -j
          sudo make install

      - name: Run Whiskit
        run: |
          find
          ./whiskit-build/whiskit --parameters="./scripts/parameters/whisker_parameters.yaml,./scripts/parameters/whisker_stimulation_parameters.yaml,./scripts/parameters/environment_parameters.yaml,./scripts/parameters/simulation_parameters.yaml"
